void main(
          float4                position        :   POSITION,
          float3                normal          :   NORMAL,

          // matrices
          uniform float4x4      model_view_project,
          
          // output to rasterizer
          out float4            out_position    :   POSITION,
          out float3            out_normal		:   TEXCOORD0)
{
	out_position = mul(model_view_project, position);
	out_normal = normal;
}